"""SQLAlchemy ORM model representing a gateway payment."""

from datetime import datetime

from sqlalchemy import DateTime, Float, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Payment(Base):
    """A single payment processed by the mock gateway.

    Attributes:
        order_id: The id of the ticket order being charged.
        amount: The charged amount.
        currency: Three-letter ISO currency code.
        status: One of pending, success, failed or refunded.
        gateway_reference: Unique reference generated by the gateway.
        created_at: When the payment record was created.
        updated_at: When the payment record was last updated.
    """

    __tablename__ = "payments"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    order_id: Mapped[int] = mapped_column(index=True)
    amount: Mapped[float] = mapped_column(Float)
    currency: Mapped[str] = mapped_column(String(3), default="USD")
    status: Mapped[str] = mapped_column(String(20), default="pending")
    gateway_reference: Mapped[str | None] = mapped_column(String(64), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now()
    )
